config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:edit, :update] 
  resources :users, only: [:show, :showself] do
    resources :follows, only: [:index, :create, :destroy]
    resources :subscriptions, only: [:index, :destroy]
    resources :groups, only: :index
  end

  resources :subscriptions

  resources :posts, only: [:show] do
    resources :comments, only: [:show, :new, :create, :destroy]
    resources :likes, only: [:index, :create, :destroy]
  end

  namespace :groups do
    get 'most_subscribers', to: 'most_subscribers'
  end

  resources :groups

  resources :groups, only: [:show] do
    resources :users, only: [:index]
    resources :posts, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  end

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post, counter_cache: true

    validates :content, presence: true, length: {in: 1..100}
    validates :post_id, presence: true
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :set_comment, only: [:show, :destroy]
    before_action :can_comment?, only: :create

    def new
        @comment = Comment.new
        @post = Post.find(params[:post_id])
    end

    def create
        @comment = Comment.new(comment_params)
        if @comment.valid?
            @comment.save
            redirect_to post_path(@comment.post_id)
        else
            render :new
        end
    end

    def show
    end

    def destroy
        if @comment.user == current_user
            @comment.destroy
            redirect_to group_post_path(@comment.post.group_id, @comment.post)
        end
    end

    private

    def can_comment?
        return true if Post.find(params[:comment][:post_id]).group.subscribers.include?(current_user)
    end

    def set_comment
        @comment = Comment.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:user_id, :post_id, :content)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_details.html.erb
<div class="comment">
        by: <%= link_to cmnt.user.username, user_path(cmnt.user) %> <%= render partial: 'users/status', locals: { group: cmnt.post.group } %>
    <br>
    <br>
    <p>
        <%= cmnt.content %>
    </p>
    <% if current_user.id == cmnt.user_id %>
        <%= button_to "Delete Comment", post_comment_path(cmnt.post, cmnt), method: :delete, data: { confirm: "Really?" } %>
    <% end %>
</div>

app/views/comments/_index.html.erb
<% if collection.empty? %>
    <p>
        There Are No Comments Yet!
        <%= button_to "Add First Comment", new_post_comment_path(@post), method: :get %>
    </p>

    <br>

<% else %>
    <%= button_to "Add New Comment", new_post_comment_path(@post), method: :get %>

    <br>

    <% collection.each do |cmnt| %>
        <%= render 'comments/comment_details', cmnt: cmnt %>
        <br>
    <% end %>

<% end %>

app/views/comments/new.html.erb
<%= render partial: 'posts/post_details', locals: { post: @post } %>

<%= form_tag post_comments_path do %>
    
  <%= render "devise/shared/error_messages", resource: @comment %>

    <%= hidden_field_tag :'comment[user_id]', current_user.id %> 
    <%= hidden_field_tag :'comment[post_id]', @post.id %> 

    <br>
    <div class="field<%= ' field_with_errors' if @comment.errors[:content].any? %>">
        <label> Comment Content: </label>
        <%= text_area_tag :'comment[content]' %>
        <br>
    </div>
    

    <%= submit_tag "Add Comment" %>
<% end %>