config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:edit, :update] 
  resources :users, only: [:show, :showself] do
    resources :follows, only: [:index, :create, :destroy]
    resources :subscriptions, only: [:index, :destroy]
    resources :groups, only: :index
  end

  resources :subscriptions

  resources :posts, only: [:show] do
    resources :comments, only: [:show, :new, :create, :destroy]
    resources :likes, only: [:index, :create, :destroy]
  end

  namespace :groups do
    get 'most_subscribers', to: 'most_subscribers'
  end

  resources :groups

  resources :groups, only: [:show] do
    resources :users, only: [:index]
    resources :posts, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  end

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/group.rb
class Group < ApplicationRecord
    

    has_many :subscriptions
    has_many :subscribers, -> { Subscription.accepted },  class_name: "User", foreign_key: "user_id", through: :subscriptions
    has_many :invitees, -> { Subscription.invited },  class_name: "User", foreign_key: "user_id", through: :subscriptions
    has_many :requests, -> { Subscription.invited }, through: :subscriptions
    belongs_to :mod, class_name: 'User'

    has_many :posts

    validates :name, uniqueness: true, presence: true, length: { in: 4..15 }, format: { with: /\A[a-zA-Z0-9 ]+\z/, message: "does not allow special characters" }
    validates :bio, length: { in: 1..50 }
    validates :mod_id, presence: true

    after_create :create_first_subscriber
    after_destroy :clear_house

    def filter_posts_by(params)
        if params[:filter].include?("Most")
            self.posts.order("#{params[:filter].split(" ")[1].downcase}_count DESC")
        elsif params[:filter] == "Recent Posts"
            self.recent_posts
        elsif params[:filter] == "Old Posts"
            self.old_posts            
        end
    end

    def valid_poster?(user)
        return true if self.subscribers.include?(user)
    end

    def recent_posts
        self.posts.order("created_at DESC")
    end
    
    def old_posts
        self.posts.order("created_at ASC")
    end

    def create_first_subscriber
        Subscription.create(user_id: mod_id, group_id: self.id, moderator: true, confirmed: true)
    end

    def clear_house
        self.posts.each do |post|
            post.comments.destroy_all
            post.likes.destroy_all
        end
        self.subscriptions.destroy_all
    end

    def self.most_subscribers
        Group.order("subscribers_count DESC").first 
    end
    

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    before_action :set_group, only: [:show, :edit, :update, :destroy]
    before_action :permitted?, only: :show
    before_action :moderator?, only: [:edit, :update, :destroy]

    def index
        @user = User.find(params[:user_id])
    end

    def new
        @group = Group.new
    end

    def create
        @group = Group.create(group_params)
        if @group.valid?
            @group.save
            redirect_to group_path(@group), flash: { notice: "Group Successfully Created" }
        else
            render :new
        end
    end

    def show
        if !params[:filter].blank?
            @posts = @group.filter_posts_by(params)
        else
            @posts = @group.posts
        end
    end

    def most_subscribers
        @group = Group.most_subscribers
    end

    def edit
    end

    def update
        if @group.update(group_params)
            redirect_to group_path(@group), flash: { notice: "Group Successfully Updated" }
        else
            redirect_to group_path(@group), flash: { error: "Group Unsuccessfully Updated" }
        end
    end

    def destroy
        if @group.destroy
            redirect_to user_path(current_user), flash: { notice: "Group Successfully Deleted" }
        else
            redirect_to user_group_path(current_user), flash: { error: "Unsuccessful Deletion" }
        end
    end

    private

    def set_group
        @group = Group.find(params[:id])
    end

    def moderator?
        if @group.moderator == current_user
            return true
        else
            @group.errors.add(:mod, "You're Not A Moderator")
            redirect_to group_path(@group)
        end
    end

    def permitted?
        if @group.subscribers.include?(current_user) || @group.invitees.include?(current_user)
            return true
        else
            redirect_to user_path(current_user), flash: { error: "You're Not Permitted"}
        end
    end

    def group_params
        params.require(:group).permit(:name, :bio, :mod_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper

    def confirmed_member(group)
        return true if group.subscribers.include?(current_user)
    end

    def current_group
        Group.find(params[:group_id])
    end

    def in_a_group?
        return true if params[:group_id]
    end
end

app/views/groups/_header.html.erb
<h1 style="text-align: center;"> <%= group.name %> </h1>

<br> 

<p style="text-align: center;">
    "<%= group.bio %>"
</p>

<br>

<%= render "layouts/gnavbar", group: group %>

<%= render "devise/shared/error_messages", resource: group %>

app/views/groups/_info.html.erb
<div class="group_inv2">
        <h3 class="title_link2"><%= link_to group.name.upcase, group_path(group) %></h3>
        <ul>
        <div class="group_info">
            <li> "<%= group.bio %>" </li>
            <br>
            
            <b style="border-bottom: 2px solid red;">Moderator </b><li><%= link_to group.mod.username, user_path(group.mod) %></li>
            <br>

            <li>Members: </li>

            <% if group.subscribers.size == 1 %>

                <li style="text-align: center;">No Members</li>

            <% else %>

                <% group.subscribers.each do |user| %>
                    <% unless user == group.mod %>
                        <p><%= link_to user.username, user_path(user) %></p>
                    <% end %>
                <% end %>

            <% end %>
        </div>
        </ul>
        <br>

        <% if current_user == group.mod %>
            <p style="text-align: right; font-size: 12px;"><%= link_to "Delete Group", group, method: :delete, data: { confirm: "Really?" } %></p>
        <% elsif ask_to_join?(current_user, group) %>
            <%= form_tag subscriptions_path do %>
                <%= hidden_field_tag :'subscription[user_id]', current_user.id %>
                <%= render partial: 'subscriptions/hidden_values', locals: { group: group } %>
                <%= submit_tag "Request to Join" %>
            <% end %>   
        <% end %>
        
    </div>
    <br>

app/views/groups/edit.html.erb
<%= render 'header', group: @group %>
<%= form_for @group do |f| %>
    <%= render "devise/shared/error_messages", resource: @group %>
    <%= f.text_field :name %>
    <%= f.text_area :bio %>
    <%= f.submit %>
<% end %>

app/views/groups/index.html.erb
<h1 style="text-align: center;"><%= @user.display_name%>'s Groups: </h1>
<br>
<br>

<%= render "devise/shared/error_messages", resource: @user %>

<% if current_user == @user %>
    <%= link_to "Create New Group", new_group_path %>

    <% if @user.subscriptions.invited.empty? %>
        <h4 style="color: red; text-align: center;">Your Pending Group Invites Would Appear Here </h4>
    <% else %>
        <div class="container">
            <div class="invitations">
                <h2> Invitations </h2>
                <%= render partial: "subscriptions/invite_index", collection: @user.subscriptions.invited, as: :sub || "No Pending Invites" %>
            </div>
        </div>
    <% end %>
<% end %>

<br>
<br>

<div class="spacer">
</div>

<% if @user.groups.empty? %>
    <% if current_user != @user %>
        <p> <%= @user.display_name %> Doesn't Belong to any Groups! </p>
    <% end %>
<% else %>
    <div class="joined_groups">
        <h2> Joined Groups: </h2>
        <%= render partial: 'info', collection: @user.groups, as: :group || "You Don't Belong to any Groups!" %>
    </div>
<% end %>
    <br>

app/views/groups/most_subscribers.html.erb
<h3>Most Subscribed Group!</h3>

<br>
<%= render "info", group: @group %>

app/views/groups/new.html.erb
<%= form_tag groups_path do %>
    
    <%= render "devise/shared/error_messages", resource: @group %>

    <br>

    <%= hidden_field_tag :'group[mod_id]', current_user.id %> 
    
    <div class="field<%= ' field_with_errors' if @group.errors[:name].any? %>">
        <label>Group Name: </label>
        <%= text_field_tag :'group[name]' %>
        <br>
    </div>
    
    <div class="field<%= ' field_with_errors' if @group.errors[:bio].any? %>">
        <label>Group Bio: </label>
        <%= text_field_tag :'group[bio]' %>
        <br>
    </div>
    <%= submit_tag "Create Group"%>
<% end %>
    

app/views/groups/show.html.erb
<%= render 'header', group: @group %>

<b>Moderator: </b><%= link_to @group.mod.username, user_path(@group.mod) %>
<br>
<br>


<br>

<% if @posts %>
    <% if @posts.empty? %>
        <p> There Are No Posts Yet! </p>
    <% else %>
        <div style="text-align:center;">

            <h3 >Filter posts:</h3>
            
            <%= form_tag group_path(@group), method: :get do %>
                <%= select_tag "filter", options_for_select(["Most Likes", "Most Comments", "Recent Posts", "Old Posts"]), include_blank: true %>
                <%= submit_tag "Filter" %>
            <% end %>

        </div>

        <%= render partial: 'posts/post_details', collection: @posts, as: :post || "There Are No Posts Yet!" %>
    <% end %>
<% end %>