config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:edit, :update] 
  resources :users, only: [:show, :showself] do
    resources :follows, only: [:index, :create, :destroy]
    resources :subscriptions, only: [:index, :destroy]
    resources :groups, only: :index
  end

  resources :subscriptions

  resources :posts, only: [:show] do
    resources :comments, only: [:show, :new, :create, :destroy]
    resources :likes, only: [:index, :create, :destroy]
  end

  namespace :groups do
    get 'most_subscribers', to: 'most_subscribers'
  end

  resources :groups

  resources :groups, only: [:show] do
    resources :users, only: [:index]
    resources :posts, only: [:new, :show, :edit, :update, :create, :destroy]
    resources :subscriptions, only: [:new, :create, :edit, :update, :destroy]
  end

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_many :comments
    has_many :likes
    has_many :likers, foreign_key: 'user_id', class_name: 'User', through: :likes

    validates :title, presence: true, length: { maximum: 30 }, format: { with: /\A[a-zA-Z0-9 ]+\z/, message: "does not allow special characters" }
    validates :content, presence: true, length: { maximum: 500 }
    validates :group_id, presence: true

    
    # scope :desc, order("posts.created_at DESC")

    

    private

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :update, :edit, :destroy]
  before_action :can_post?, only: :create
  before_action :can_view?, only: :show

  def index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to group_path(id: params[:group_id])
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if post_params
      @post.update(title: "EDITED #{params[:post][:title]}", content: "EDITED #{params[:post][:content]}")
      @post.save
      redirect_to group_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy
      redirect_to group_path(params[:group_id])
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def can_view?
    if @post.group.subscribers.include?(current_user) || @post.group.invitees.include?(current_user)
      return true
    else
      redirect_to user_path(current_user), flash: { notice: "Cannot View Post" }
    end
  end

  def can_post?
    if Group.find(params[:group_id]).valid_poster?(current_user)
      return true 
    else
      redirect_to group_path(params[:group_id]), flash: { notice: "Cannot Post" }
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :group_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

    def current_post
        @post = Post.find(params[:post_id])
    end


    

end

app/views/posts/_post_details.html.erb
<br>
<div class="container">
    <div class="post_div">

        <div class="post_div_title">
            <h1><%= link_to post.title, group_post_path(post.group, post) %></h1>
            <p>
                By: <%= link_to post.user.display_name, user_path(post.user_id) %> || <%= render partial: 'users/status', locals: { group: post.group, user: post.user } %>
            </p>
        </div>

        <br>

        <div class="post_div_body">
            <p><%= post.content %></p>
        </div>

        <br>
        <br>

            
            <% if current_user.id != post.user_id %>
                <% if post.group.subscribers.include?(current_user) %>
                    <p class="post_likes">
                        <%= post.likes.count %> <%= link_to "Likes", post_likes_path(post), method: :get %>  || <%= render partial: "likes/like_button", locals: { post: post } %>
                    </p>
                <% end %>
                
               
            <% else %>
                <p class="post_likes">
                    <%= post.likes.count %> <%= link_to "Likes", post_likes_path(post), method: :get %>
                </p>
                <%= link_to "Edit Post", edit_group_post_path(post.group_id, post) %>
                <%= link_to "Delete Post", group_post_path(post.group_id, post), method: :delete, data: { confirm: "Really?" } %>
            <% end %>

        
    </div>
</div>
<br>

app/views/posts/edit.html.erb
<%= form_for @post, url: group_post_path(@post.group, @post), method: :patch do |f| %>
    <%= render "devise/shared/error_messages", resource: @post %>
    <%= f.text_field :title %>
    <%= f.text_area :content %>
    <%= f.submit "Update Post" %>
<% end %>

app/views/posts/new.html.erb
<%= render 'groups/header', group: current_group %>
<%= form_tag group_posts_path do %>
    
  <%= render "devise/shared/error_messages", resource: @post %>

  <br>

    <%= hidden_field_tag :'post[user_id]', current_user.id %> 
    <%= hidden_field_tag :'post[group_id]', current_group.id %> 

    <div class="field<%= ' field_with_errors' if @post.errors[:title].any? %>">
        <label>Post Title: </label>
        <%= text_field_tag :'post[title]' %>
        <br>
    </div>

    <div class="field<%= ' field_with_errors' if @post.errors[:content].any? %>">
        <label>Post Content: </label>
        <%= text_field_tag :'post[content]' %>
        <br>
    </div>
    <%= submit_tag "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<%= render 'post_details', post: @post %>

<br>


<br>
<%= if @post.group.subscribers.include?(current_user) %>
    <%= render 'comments/index', collection: @post.comments, object: @post %>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>